import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.Finiteness.Basic

/-
HANDWRITTEN PROOF TO FOLLOW: https://math.gsu.edu/fenescu/commalglectures/lect20.pdf

THRM:
Let R be a positively graded R_0-algebra. Let x_1, ..., x_n be elements of
positive degree. Then (x_1, ..., x_n) = bigoplus_{i=1}^∞ R_i ... only if {x_1, ..., x_n} generates R
as an R_0-algebra.

PROOF:
...we proceed by induction on the degree of y. If deg y = 0,
the proof is clear, so assume a positive degree. We have y ∈ (x_1, ..., x_n), so y = α_1x_1 +
··· + α_nx_n, with α_i ∈ R, and if deg x_i = d_i, then α_i ∈ R_{deg y−d_i} . To finish, apply the
induction hypothesis to the α_i’s.
-/

/-
If `R₊` is finitely generated as an ideal, then `R` is finitely generated as an algebra over the
degree-`0` graded piece `𝒜 0`.  To conclude finite generation over the base field `k`, you still
need a separate hypothesis that `𝒜 0` is finitely generated as a `k`-algebra (then apply
transitivity); that extra hypothesis cannot be dropped in general.
-/

namespace GIT

section

universe uR

variable {k : Type u} [Field k]
variable {R : Type uR} [CommRing R] [Algebra k R]
variable {𝒜 : ℕ → Submodule k R} [GradedAlgebra 𝒜]

open scoped DirectSum
open scoped BigOperators

/-!
Pseudo-code blueprint for the proof.

High-level idea:

- From `h : (irrelevant 𝒜).toIdeal.FG`, pick a finite set `S` generating the irrelevant ideal.
- Replace `S` by the finite set of homogeneous components of elements of `S`.
  (So we may assume `S ⊆ ⋃ i > 0, 𝒜 i` and consists of homogeneous elements.)
- Prove by strong induction on `d : ℕ`:
  every `y ∈ 𝒜 d` lies in the subalgebra of `R` generated (over `𝒜 0`) by `S`.
  For `d = 0` this is trivial; for `d > 0`, use `y ∈ irrelevant` to write
  `y = ∑ a_j * s_j` with `s_j ∈ S`, and then show each `a_j` has smaller degree,
  so by IH each `a_j` is in the subalgebra, hence so is `y`.
- Conclude `Algebra.FiniteType (𝒜 0) R`. For `Algebra.FiniteType k R`, combine with
  `[Algebra.FiniteType k (𝒜 0)]` via transitivity (see corollary below).
-/

/- Step 0: convenience notation for the irrelevant ideal as an `Ideal R`. -/
abbrev irrelevantIdeal : Ideal R := (HomogeneousIdeal.irrelevant 𝒜).toIdeal

/- Step 1: homogenize the generating set.

Given `S` generating the irrelevant ideal, we want a finite `T` consisting of homogeneous
elements of positive degree that still generates the same ideal.

This is the “take all homogeneous components of each generator” step.
-/
lemma exists_finset_homogeneous_pos_generators
    (h : (irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜)).FG) :
    ∃ T : Finset R,
      (Ideal.span (T : Set R) = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜)) ∧
      (∀ t ∈ T, ∃ d : ℕ, 0 < d ∧ t ∈ 𝒜 d) := by
  classical
  -- Let `s` be the set of positive-degree homogeneous elements.
  let s : Set R := ⋃ i : ℕ, ⋃ _ : 0 < i, (𝒜 i : Set R)
  -- The irrelevant ideal is the ideal span of `s`.
  have hirr : irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) = Ideal.span s := by
    -- This is exactly `HomogeneousIdeal.irrelevant_eq_span`.
    simpa [irrelevantIdeal, s] using (HomogeneousIdeal.irrelevant_eq_span (𝒜 := 𝒜))
  -- Convert `h : irrelevantIdeal.FG` into `FG (Ideal.span s)`.
  have hspan_s_fg : (Ideal.span s : Ideal R).FG := by
    rcases h with ⟨S, hS⟩
    refine ⟨S, ?_⟩
    -- rewrite target ideal using `hirr` (avoid `simp` unfolding `irrelevantIdeal` to a kernel)
    calc
      Ideal.span (S : Set R)
          = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) := hS
      _   = Ideal.span s := hirr
  -- Use the general lemma: a finitely generated span has a finite subset of generators.
  -- (This is stated for submodules, but `Ideal.span` is defeq `Submodule.span`.)
  have hfg_submodule : (Submodule.span R s).FG := by
    rcases hspan_s_fg with ⟨S, hS⟩
    refine ⟨S, ?_⟩
    -- Avoid `simp [Ideal.span]` recursion: coerce the ideal equality to a submodule equality.
    have hS' :
        (Ideal.span (S : Set R) : Submodule R R) = (Ideal.span s : Submodule R R) :=
      congrArg (fun (I : Ideal R) => (I : Submodule R R)) hS
    -- Don't unfold anything: just change the goal to match `hS'`.
    change (Ideal.span (S : Set R) : Submodule R R) = (Ideal.span s : Submodule R R)
    exact hS'
  rcases (Submodule.fg_span_iff_fg_span_finset_subset (R := R) (M := R) s).1 hfg_submodule with
    ⟨T, hTs, hspan⟩
  refine ⟨T, ?_, ?_⟩
  · -- show the ideal generated by `T` is the irrelevant ideal
    -- We have `Submodule.span R s = Submodule.span R (T : Set R)`.
    -- Convert to ideals and use `hirr`.
    have : Ideal.span s = Ideal.span (T : Set R) := by
      -- Convert the submodule equality into an ideal equality, then unfold `Ideal.span` once.
      have hspan' : (Submodule.span R s : Ideal R) = (Submodule.span R (T : Set R) : Ideal R) :=
        congrArg (fun (N : Submodule R R) => (N : Ideal R)) hspan
      -- Again, avoid unfolding: just change the goal to match `hspan'`.
      change (Ideal.span s : Ideal R) = (Ideal.span (T : Set R) : Ideal R)
      exact hspan'
    -- Rearrange to match the goal, without unfolding `irrelevantIdeal` to a kernel.
    calc
      Ideal.span (T : Set R) = Ideal.span s := this.symm
      _ = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) := hirr.symm
  · intro t ht
    -- Use `t ∈ T` ⇒ `t ∈ s` from `hTs`, then unpack membership in the union.
    have : t ∈ s := hTs (by simpa using ht)
    -- `t ∈ ⋃ i, ⋃ (_:0<i), 𝒜 i` gives the desired degree.
    rcases Set.mem_iUnion.1 this with ⟨d, hd⟩
    rcases Set.mem_iUnion.1 hd with ⟨hdpos, hmem⟩
    exact ⟨d, hdpos, hmem⟩

/- Step 2: set up the intermediate base algebra `𝒜 0 →ₐ[k] R`.

In a graded algebra, the degree-0 part is a subalgebra; there is an induced algebra structure.
We’ll want `Algebra.FiniteType (𝒜 0) R` and then use `Algebra.FiniteType.trans`.

This lemma is a placeholder for the typeclass plumbing (it may already be inferable).
-/
noncomputable def inst_algebra_degreeZero :
    Algebra (𝒜 0) R := by
  classical
  -- This instance is provided by Mathlib from `[GradedAlgebra 𝒜]`.
  exact inferInstance

noncomputable def inst_isScalarTower_degreeZero :
    IsScalarTower k (𝒜 0) R := by
  classical
  -- This is *not* always found automatically by typeclass search, so we build it explicitly
  -- from the compatibility of `algebraMap`s.
  letI : Algebra (𝒜 0) R := inst_algebra_degreeZero (k := k) (R := R) (𝒜 := 𝒜)
  refine IsScalarTower.of_algebraMap_eq' (R := k) (S := (𝒜 0)) (A := R) ?_
  -- `simp` should know that the map `(𝒜 0) → R` is the coercion, so the tower condition is
  -- definitional.
  ext x
  simp

/- Step 3: if finite positive-degree homogeneous `T` spans the irrelevant ideal, then every
`𝒜 d` lies in `Algebra.adjoin (𝒜 0) T`.

Strong induction on `d`. Degree `0`: `y ∈ 𝒜 0` embeds in the adjoin. For `d > 0`, `y` lies in
the irrelevant ideal hence in `Ideal.span T`; pick `y = ∑ l t * t`, apply the degree-`d` graded
projection (which fixes `y`) and push it through the sum. For each `t`, graded multiplication with
homogeneous `t` identifies the degree-`d` piece of `l t * t` with `(decompose (l t)) (d - deg t) * t`
when `deg t ≤ d`; that graded piece has degree `< d`, so IH covers it, then multiply by `t` in the
adjoin. If `deg t > d`, the projection is `0`. Sum and `mul` closure finish.
-/

lemma homogeneous_mem_adjoin_of_irrelevant_eq_span
    {T : Finset R}
    (hspan : Ideal.span (T : Set R) = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜))
    (hT : ∀ t ∈ T, ∃ d : ℕ, 0 < d ∧ t ∈ 𝒜 d) :
    ∀ d : ℕ, ∀ y : R, y ∈ 𝒜 d → y ∈ Algebra.adjoin (𝒜 0) (T : Set R) := by
  classical
  -- We prove the claim by strong induction on `d`.
  intro d
  refine Nat.strong_induction_on d ?_
  intro d ih y hy
  by_cases hd0 : d = 0
  · -- degree 0: `y` comes from the base algebra `𝒜 0`.
    subst hd0
    -- View `y` as an element of `𝒜 0` and use `Subalgebra.algebraMap_mem`.
    -- (The `Algebra (𝒜 0) R` instance is provided by step 2.)
    have : y ∈ (Algebra.adjoin (𝒜 0) (T : Set R) : Subalgebra (𝒜 0) R) := by
      -- `⟨y, hy⟩ : 𝒜 0` maps to `y` in `R`.
      simpa using (Subalgebra.algebraMap_mem (Algebra.adjoin (𝒜 0) (T : Set R)) ⟨y, hy⟩)
    exact this
  · -- positive degree:
    have hdpos : 0 < d := Nat.pos_of_ne_zero hd0
    -- First show `y ∈ irrelevantIdeal`.
    have hy_irrel : y ∈ irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) := by
      -- `HomogeneousIdeal.mem_irrelevant_of_mem` gives membership in the *homogeneous* ideal.
      have : y ∈ HomogeneousIdeal.irrelevant 𝒜 := by
        exact HomogeneousIdeal.mem_irrelevant_of_mem (𝒜 := 𝒜) (x := y) (i := d) hdpos hy
      -- Coerce to the underlying ideal.
      simpa [irrelevantIdeal] using this
    -- Rewrite using the spanning hypothesis.
    have hy_span : y ∈ Ideal.span (T : Set R) := by
      -- `hspan : Ideal.span T = irrelevantIdeal`, so use it backwards.
      simpa [hspan] using hy_irrel
    -- Extract an explicit finite `T`-linear combination for `y`.
    have hy_span' : y ∈ (Submodule.span R (T : Set R) : Submodule R R) := by
      -- `Ideal.span` is defeq `Submodule.span` on `R`.
      change y ∈ ((Ideal.span (T : Set R) : Ideal R) : Submodule R R)
      exact hy_span
    rcases
        (Finsupp.mem_span_iff_linearCombination (R := R) (M := R) (s := (T : Set R)) y).1 hy_span'
      with ⟨l, hl⟩

    -- Choose a positive degree for each generator `t ∈ T`.
    choose degT hdegTpos hdegTmem using (fun t : (T : Set R) => (hT t.1 (by simpa using t.2)))

    -- Let `π_d : R →+ R` be the degree-`d` projection `z ↦ (decompose z d : R)`.
    let πd : R →+ R :=
      { toFun := fun z => ((DirectSum.decompose 𝒜 z) d : R)
        map_zero' := by simp
        map_add' := by simp }

    -- Since `y ∈ 𝒜 d`, `π_d y = y`.
    have hπy : πd y = y := by
      simpa [πd] using (DirectSum.decompose_of_mem_same 𝒜 (x := y) (i := d) hy)

    -- Expand the span expression `hl` as a concrete finset sum in `R`.
    have hl_sum :
        (Finsupp.linearCombination R (fun t : (T : Set R) => (t : R)) l) =
          Finset.sum l.support (fun t => l t * (t : R)) := by
      classical
      simpa [Finsupp.linearCombination_apply, smul_eq_mul, Finsupp.sum]

    -- Apply `πd` to `hl` and rewrite the RHS as a sum of `πd` applied to each summand.
    have hproj :
        y = Finset.sum l.support (fun t => πd (l t * (t : R))) := by
      -- start from `πd (linearCombination ...) = πd y`
      have h1 : πd (Finsupp.linearCombination R (fun t : (T : Set R) => (t : R)) l) = πd y := by
        simpa [hl] using congrArg πd hl
      -- rewrite the `linearCombination` as a finset sum and push `πd` inside
      have h1' : πd (Finset.sum l.support (fun t => l t * (t : R))) = πd y := by
        -- use `rw` (not `simp`) to avoid rewriting `πd` across the sum
        have h1' := h1
        rw [hl_sum] at h1'
        exact h1'
      have h2 : Finset.sum l.support (fun t => πd (l t * (t : R))) = πd y := by
        simpa [map_sum] using h1'
      -- use `πd y = y` since `y` is homogeneous of degree `d`
      have h3 : Finset.sum l.support (fun t => πd (l t * (t : R))) = y := by
        simpa [hπy] using h2
      exact h3.symm

    -- Each summand `πd (l t * t)` lies in the adjoin, hence their sum (and thus `y`) lies in the adjoin.
    have hsum_mem :
        (Finset.sum l.support (fun t => πd (l t * (t : R)))) ∈
          Algebra.adjoin (𝒜 0) (T : Set R) := by
      classical
      refine (Subsemiring.sum_mem (Algebra.adjoin (𝒜 0) (T : Set R)).toSubsemiring) ?_
      intro t ht_support
      -- `t` itself is a generator, hence in the adjoin.
      have ht_mem : (t : R) ∈ Algebra.adjoin (𝒜 0) (T : Set R) :=
        Algebra.subset_adjoin t.2
      -- Use graded projection lemma on the product `(l t) * t`.
      have ht_hom : (t : R) ∈ 𝒜 (degT t) := by
        simpa using (hdegTmem t)
      by_cases hle : degT t ≤ d
      · have hπ :
            πd (l t * (t : R)) =
              ((DirectSum.decompose 𝒜 (l t)) (d - degT t) : R) * (t : R) := by
          simpa [πd] using
            (DirectSum.coe_decompose_mul_of_right_mem_of_le (𝒜 := 𝒜)
              (a := l t) (b := (t : R)) (n := d) (i := degT t) ht_hom hle)
        have hlt : d - degT t < d :=
          Nat.sub_lt (Nat.pos_of_ne_zero (Nat.ne_of_gt hdpos)) (hdegTpos t)
        have hcoeff_mem :
            ((DirectSum.decompose 𝒜 (l t)) (d - degT t) : R) ∈
              Algebra.adjoin (𝒜 0) (T : Set R) := by
          have hcoeff_hom :
              ((DirectSum.decompose 𝒜 (l t)) (d - degT t) : R) ∈ 𝒜 (d - degT t) :=
            ((DirectSum.decompose 𝒜 (l t)) (d - degT t)).2
          exact ih (d - degT t) hlt _ hcoeff_hom
        -- rewrite the goal using `hπ`, then use closure under multiplication
        rw [hπ]
        exact
          (Subsemiring.mul_mem (Algebra.adjoin (𝒜 0) (T : Set R)).toSubsemiring hcoeff_mem ht_mem)
      · have hπ0 : πd (l t * (t : R)) = 0 := by
          simpa [πd] using
            (DirectSum.coe_decompose_mul_of_right_mem_of_not_le (𝒜 := 𝒜)
              (a := l t) (b := (t : R)) (n := d) (i := degT t) ht_hom hle)
        -- rewrite the goal using `hπ0`
        rw [hπ0]
        simpa using (Subsemiring.zero_mem (Algebra.adjoin (𝒜 0) (T : Set R)).toSubsemiring)

    simpa [hproj] using hsum_mem

/- Step 4: package the induction into an `Algebra.FiniteType (𝒜 0) R` statement.

Once you know every element of `R` lies in `Algebra.adjoin (𝒜 0) T`, you conclude the adjoin is `⊤`,
and therefore `R` is `Algebra.FiniteType` over `𝒜 0`.
-/
lemma finiteType_degreeZero_of_irrelevant_fg
    (h : (irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜)).FG) :
    Algebra.FiniteType (𝒜 0) R := by
  classical
  obtain ⟨T, hspan, hT⟩ := exists_finset_homogeneous_pos_generators (k := k) (R := R) (𝒜 := 𝒜) h
  -- `Algebra.FiniteType (𝒜 0) R` means `(⊤ : Subalgebra (𝒜 0) R).FG`, i.e. some finset adjoins to `⊤`.
  refine ⟨⟨T, ?_⟩⟩
  rw [eq_top_iff]
  intro r _
  -- Write `r` as a finite sum of its homogeneous components.
  rw [← DirectSum.sum_support_decompose 𝒜 r]
  refine Subalgebra.sum_mem (Algebra.adjoin (𝒜 0) (T : Set R)) ?_
  intro i _
  -- Each graded piece lies in `𝒜 i`, hence in the adjoin by the induction lemma.
  have hy : ((DirectSum.decompose 𝒜 r) i : R) ∈ 𝒜 i :=
    SetLike.coe_mem ((DirectSum.decompose 𝒜 r) i)
  exact homogeneous_mem_adjoin_of_irrelevant_eq_span (𝒜 := 𝒜) hspan hT i _ hy

/- Final theorem: finitely generated irrelevant ideal implies `R` is finitely generated over `𝒜 0`.

No assumption on how `𝒜 0` sits over `k`; that is exactly the content of `finiteType_degreeZero_of_irrelevant_fg`.
-/
theorem finiteType_of_finitely_generated_irrelevant_ideal
    (h : (HomogeneousIdeal.irrelevant 𝒜).toIdeal.FG) :
    Algebra.FiniteType (𝒜 0) R :=
  finiteType_degreeZero_of_irrelevant_fg (k := k) (R := R) (𝒜 := 𝒜) (h := by
    simpa [irrelevantIdeal] using h)

/- Corollary over `k`: combine the theorem above with finite generation of `𝒜 0` over `k`. -/
theorem finiteType_k_of_finitely_generated_irrelevant_ideal
    [Algebra.FiniteType k (𝒜 0)] (h : (HomogeneousIdeal.irrelevant 𝒜).toIdeal.FG) :
    Algebra.FiniteType k R := by
  classical
  letI : Algebra (𝒜 0) R := inst_algebra_degreeZero (k := k) (R := R) (𝒜 := 𝒜)
  letI : IsScalarTower k (𝒜 0) R := inst_isScalarTower_degreeZero (k := k) (R := R) (𝒜 := 𝒜)
  exact Algebra.FiniteType.trans (R := k) (S := 𝒜 0) (A := R)
    (hRS := inferInstance) (hSA := finiteType_of_finitely_generated_irrelevant_ideal h)
end

end GIT

/- April 20 Meeting Notes

y in R_d^G implies R_0^G[x_1, ... , x_r]
induction on d:
  - use generalizing y, because we use inductive hypothesis on alpha
  - use stong induction instead of normal induction
-/
