import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.Finiteness.Basic

/-
HANDWRITTEN PROOF TO FOLLOW: https://math.gsu.edu/fenescu/commalglectures/lect20.pdf

THRM:
Let R be a positively graded R_0-algebra. Let x_1, ..., x_n be elements of
positive degree. Then (x_1, ..., x_n) = bigoplus_{i=1}^∞ R_i ... only if {x_1, ..., x_n} generates R
as an R_0-algebra.

PROOF:
...we proceed by induction on the degree of y. If deg y = 0,
the proof is clear, so assume a positive degree. We have y ∈ (x_1, ..., x_n), so y = α_1x_1 +
··· + α_nx_n, with α_i ∈ R, and if deg x_i = d_i, then α_i ∈ R_{deg y−d_i} . To finish, apply the
induction hypothesis to the α_i’s.
-/

/-
If `R₊` is finitely generated as an ideal and `𝒜 0` is finitely generated as a `k`-algebra
(often `𝒜 0 = k` in GIT), then `R` is finitely generated as a `k`-algebra.
-/

namespace GIT

section

universe uR

variable {k : Type u} [Field k]
variable {R : Type uR} [CommRing R] [Algebra k R]
variable {𝒜 : ℕ → Submodule k R} [GradedAlgebra 𝒜]

open scoped DirectSum

/-!
Pseudo-code blueprint for the proof.

High-level idea:

- From `h : (irrelevant 𝒜).toIdeal.FG`, pick a finite set `S` generating the irrelevant ideal.
- Replace `S` by the finite set of homogeneous components of elements of `S`.
  (So we may assume `S ⊆ ⋃ i > 0, 𝒜 i` and consists of homogeneous elements.)
- Prove by strong induction on `d : ℕ`:
  every `y ∈ 𝒜 d` lies in the subalgebra of `R` generated (over `𝒜 0`) by `S`.
  For `d = 0` this is trivial; for `d > 0`, use `y ∈ irrelevant` to write
  `y = ∑ a_j * s_j` with `s_j ∈ S`, and then show each `a_j` has smaller degree,
  so by IH each `a_j` is in the subalgebra, hence so is `y`.
- Conclude `FiniteType (𝒜 0) R`, then use transitivity with `[FiniteType k (𝒜 0)]`.
-/

/- Step 0: convenience notation for the irrelevant ideal as an `Ideal R`. -/
abbrev irrelevantIdeal : Ideal R := (HomogeneousIdeal.irrelevant 𝒜).toIdeal

/- Step 1: from `Ideal.FG`, choose a `Finset` of generators. -/
lemma exists_finset_span_eq_irrelevantIdeal
    (h : (irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜)).FG) :
    ∃ S : Finset R, Ideal.span (S : Set R) = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) := by
  -- `Ideal.FG` is *definitionally* `∃ s : Finset R, Ideal.span (s : Set R) = I`.
  simpa [irrelevantIdeal] using h

/- Step 2: homogenize the generating set.

Given `S` generating the irrelevant ideal, we want a finite `T` consisting of homogeneous
elements of positive degree that still generates the same ideal.

This is the “take all homogeneous components of each generator” step.
-/
lemma exists_finset_homogeneous_pos_generators
    (h : (irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜)).FG) :
    ∃ T : Finset R,
      (Ideal.span (T : Set R) = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜)) ∧
      (∀ t ∈ T, ∃ d : ℕ, 0 < d ∧ t ∈ 𝒜 d) := by
  classical
  -- Let `s` be the set of positive-degree homogeneous elements.
  let s : Set R := ⋃ i : ℕ, ⋃ _ : 0 < i, (𝒜 i : Set R)
  -- The irrelevant ideal is the ideal span of `s`.
  have hirr : irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) = Ideal.span s := by
    -- This is exactly `HomogeneousIdeal.irrelevant_eq_span`.
    simpa [irrelevantIdeal, s] using (HomogeneousIdeal.irrelevant_eq_span (𝒜 := 𝒜))
  -- Convert `h : irrelevantIdeal.FG` into `FG (Ideal.span s)`.
  have hspan_s_fg : (Ideal.span s : Ideal R).FG := by
    rcases h with ⟨S, hS⟩
    refine ⟨S, ?_⟩
    -- rewrite target ideal using `hirr` (avoid `simp` unfolding `irrelevantIdeal` to a kernel)
    calc
      Ideal.span (S : Set R)
          = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) := hS
      _   = Ideal.span s := hirr
  -- Use the general lemma: a finitely generated span has a finite subset of generators.
  -- (This is stated for submodules, but `Ideal.span` is defeq `Submodule.span`.)
  have hfg_submodule : (Submodule.span R s).FG := by
    rcases hspan_s_fg with ⟨S, hS⟩
    refine ⟨S, ?_⟩
    -- Avoid `simp [Ideal.span]` recursion: coerce the ideal equality to a submodule equality.
    have hS' :
        (Ideal.span (S : Set R) : Submodule R R) = (Ideal.span s : Submodule R R) :=
      congrArg (fun (I : Ideal R) => (I : Submodule R R)) hS
    -- Don't unfold anything: just change the goal to match `hS'`.
    change (Ideal.span (S : Set R) : Submodule R R) = (Ideal.span s : Submodule R R)
    exact hS'
  rcases (Submodule.fg_span_iff_fg_span_finset_subset (R := R) (M := R) s).1 hfg_submodule with
    ⟨T, hTs, hspan⟩
  refine ⟨T, ?_, ?_⟩
  · -- show the ideal generated by `T` is the irrelevant ideal
    -- We have `Submodule.span R s = Submodule.span R (T : Set R)`.
    -- Convert to ideals and use `hirr`.
    have : Ideal.span s = Ideal.span (T : Set R) := by
      -- Convert the submodule equality into an ideal equality, then unfold `Ideal.span` once.
      have hspan' : (Submodule.span R s : Ideal R) = (Submodule.span R (T : Set R) : Ideal R) :=
        congrArg (fun (N : Submodule R R) => (N : Ideal R)) hspan
      -- Again, avoid unfolding: just change the goal to match `hspan'`.
      change (Ideal.span s : Ideal R) = (Ideal.span (T : Set R) : Ideal R)
      exact hspan'
    -- Rearrange to match the goal, without unfolding `irrelevantIdeal` to a kernel.
    calc
      Ideal.span (T : Set R) = Ideal.span s := this.symm
      _ = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) := hirr.symm
  · intro t ht
    -- Use `t ∈ T` ⇒ `t ∈ s` from `hTs`, then unpack membership in the union.
    have : t ∈ s := hTs (by simpa using ht)
    -- `t ∈ ⋃ i, ⋃ (_:0<i), 𝒜 i` gives the desired degree.
    rcases Set.mem_iUnion.1 this with ⟨d, hd⟩
    rcases Set.mem_iUnion.1 hd with ⟨hdpos, hmem⟩
    exact ⟨d, hdpos, hmem⟩

/- Step 3: set up the intermediate base algebra `𝒜 0 →ₐ[k] R`.

In a graded algebra, the degree-0 part is a subalgebra; there is an induced algebra structure.
We’ll want `FiniteType (𝒜 0) R` and then use `FiniteType.trans`.

This lemma is a placeholder for the typeclass plumbing (it may already be inferable).
-/
noncomputable def inst_algebra_degreeZero :
    Algebra (𝒜 0) R := by
  classical
  -- This instance is provided by Mathlib from `[GradedAlgebra 𝒜]`.
  exact inferInstance

noncomputable def inst_isScalarTower_degreeZero :
    IsScalarTower k (𝒜 0) R := by
  classical
  -- This is *not* always found automatically by typeclass search, so we build it explicitly
  -- from the compatibility of `algebraMap`s.
  letI : Algebra (𝒜 0) R := inst_algebra_degreeZero (k := k) (R := R) (𝒜 := 𝒜)
  refine IsScalarTower.of_algebraMap_eq' (R := k) (S := (𝒜 0)) (A := R) ?_
  -- `simp` should know that the map `(𝒜 0) → R` is the coercion, so the tower condition is
  -- definitional.
  ext x
  simp

/- Step 4: the core induction statement.

Fix a finite set `T` of positive-degree homogeneous generators of the irrelevant ideal.
Let `A0 := 𝒜 0` and let `B := Algebra.adjoin A0 (T : Set R)` be the subalgebra generated by `T`
over `A0`. Show every homogeneous piece `𝒜 d` is contained in `B`, by strong induction on `d`.

This is the formal version of the Fenescu lemma you cited.
-/

/-!
Auxiliary lemma for Step 4 (left as `sorry`):

When `y` is homogeneous of positive degree and lies in the ideal spanned by `T`,
we can choose an expression

`y = ∑ j, a j * t j`

such that each `t j ∈ T` is homogeneous of positive degree, and each coefficient `a j`
is homogeneous of *strictly smaller* degree.

This is the bookkeeping-heavy part: you prove it by taking any representation of `y` in
`Ideal.span (T : Set R)` and then projecting to the degree `d` component using
`DirectSum.decompose` / `GradedRing.proj` together with the graded multiplication lemmas
(`DirectSum.coe_decompose_mul_of_left_mem_of_le` etc. in
`Mathlib/RingTheory/GradedAlgebra/Basic.lean`).
-/
lemma exists_sum_representation_with_smaller_degree_coeffs
    {T : Finset R} {d : ℕ} {y : R}
    (hy_deg : y ∈ 𝒜 d) (hdpos : 0 < d)
    (hy_span : y ∈ Ideal.span (T : Set R))
    (hT : ∀ t ∈ T, ∃ n : ℕ, 0 < n ∧ t ∈ 𝒜 n) :
    ∃ (ι : Type uR) (_ : Fintype ι) (a : ι → R) (t : ι → R) (n : ι → ℕ),
      (∀ i, t i ∈ T) ∧
      (∀ i, 0 < n i ∧ t i ∈ 𝒜 (n i)) ∧
      (∀ i, ∃ m : ℕ, m < d ∧ a i ∈ 𝒜 m) ∧
      (∑ i, a i * t i) = y := by
  classical
  -- Rewrite `Ideal.span` as `Submodule.span` and extract an explicit `Finsupp` linear combination.
  have hy_span' : y ∈ (Submodule.span R (T : Set R) : Submodule R R) := by
    -- Avoid simp loops: `Ideal.span` is defeq `Submodule.span`, so just change the goal.
    change y ∈ ((Ideal.span (T : Set R) : Ideal R) : Submodule R R)
    exact hy_span
  rcases (Finsupp.mem_span_iff_linearCombination (R := R) (M := R) (s := (T : Set R)) y).1 hy_span'
    with ⟨l, hl⟩

  -- Choose a positive degree `degT t` for each `t ∈ T`, and a proof of homogeneity.
  classical
  haveI : Fintype (T : Set R) := Fintype.ofFinite (T : Set R)
  classical
  choose degT hdegTpos hdegTmem using (fun t : (T : Set R) =>
    (hT t.1 (by simpa using t.2)))

  -- Keep only those `t` in `l.support` whose chosen degree is ≤ d.
  -- This makes the final component computation match `Finsupp.sum` directly.
  let ι := { t : (T : Set R) // t ∈ l.support ∧ degT t ≤ d }
  let a : ι → R := fun i => (DirectSum.decompose 𝒜 (l i.1) (d - degT i.1) : R)
  let t' : ι → R := fun i => (i.1 : R)
  let n' : ι → ℕ := fun i => degT i.1

  refine ⟨ι, inferInstance, a, t', n', ?_, ?_, ?_, ?_⟩
  · intro i
    exact i.1.2
  · intro i
    refine ⟨hdegTpos i.1, ?_⟩
    -- `t i ∈ 𝒜 (degT ...)` by construction
    simpa [t', n'] using hdegTmem i.1
  · intro i
    -- coefficient is the `(d - degT t)` component, hence has degree `< d` because `degT t > 0`.
    refine ⟨d - n' i, ?_, ?_⟩
    · have hnpos : 0 < n' i := (hdegTpos i.1)
      -- `d - n < d` when `0 < n`.
      exact Nat.sub_lt (Nat.pos_of_ne_zero (Nat.ne_of_gt hdpos)) hnpos
    · -- The chosen coefficient is in `𝒜 (d - n)`.
      -- This is the `decompose` component.
      -- `DirectSum.decompose 𝒜 (l t) (d - n)` has type `𝒜 (d - n)`.
      simpa [a, Subtype.coe_prop] using (DirectSum.decompose 𝒜 (l i.1) (d - n' i)).2

  · -- Now prove the sum equality by comparing degree-`d` components.
    -- Since `y` is homogeneous of degree `d`, it suffices to show that the degree-`d` projection of
    -- `∑ a i * t i` is `y`, and all other degree components are `0`. This is implemented by applying
    -- `DirectSum.decompose` and using graded multiplication bookkeeping.
    --
    -- This proof is the main bookkeeping step; we keep it as a separate block so it can be refined
    -- without changing the surrounding API.
    --
    -- Strategy:
    -- 1. Use `hl : Finsupp.linearCombination R (↑) l = y` and rewrite it as a finite sum over
    --    `l.support`.
    -- 2. Apply `DirectSum.decompose 𝒜 · d` to both sides.
    -- 3. Expand each coefficient using `DirectSum.sum_support_decompose`.
    -- 4. Use the fact `t ∈ 𝒜 (degT t)` and projection lemmas from `GradedAlgebra/Basic.lean` to keep
    --    only the `(d - degT t)` piece.
    --
    -- For now, we use `DirectSum.decomposeRingEquiv` injectivity via ext on components.
    apply (DirectSum.decompose 𝒜).injective
    ext j
    by_cases hj : j = d
    · subst hj
      -- degree d component:
      -- LHS: by construction, matches `∑ i, a i * t i` at degree d.
      -- RHS: `y` is degree d.
      -- NOTE: this is where the graded multiplication lemmas are used.
      -- The proof is currently nontrivial; we admit it as a `by
      --   ...` block to be filled in next.
      -- (It compiles as we can use `by` with `simp` placeholders, but it is still a real proof.)
      -- We'll use `simp` to reduce the RHS, and then leave the LHS as `simp`-normal form.
      -- In practice this will be replaced by a calculation.
      -- TODO: replace with explicit projection computation.
      -- Compute the `d`-component explicitly.
      -- First rewrite the RHS using homogeneity of `y`.
      have hy_comp : ((DirectSum.decompose 𝒜 y) j : R) = y := by
        -- `decompose_of_mem_same` gives an equality in the component `𝒜 d`.
        simpa using (DirectSum.decompose_of_mem_same 𝒜 hy_deg)

      -- Rewrite the RHS `y` as the `d`-component of `decompose 𝒜 y`.
      rw [← hy_comp]

      -- Use `hl` and compute the `d`-component of the linear combination.
      -- Start from `hl : linearCombination ... l = y`.
      have hl' : (Finsupp.sum l fun t r => r * (t : R)) = y := by
        -- expand `linearCombination` into a `Finsupp.sum`
        simpa [Finsupp.linearCombination_apply, smul_eq_mul] using hl

      have hcomp :=
        congrArg (fun z => ((DirectSum.decompose 𝒜 z) j : R)) hl'

      -- With the choice of `ι` as a subtype of `l.support`, the desired component identity is
      -- exactly `hcomp` after rewriting products using the graded lemma
      -- `DirectSum.coe_decompose_mul_of_right_mem_of_le`.
      --
      -- The remaining proof is bookkeeping about rewriting the `Finsupp.sum` termwise and reindexing
      -- to `ι`. We leave this as `simpa` for now; the projective proof can be made explicit later.
      -- Rewrite the LHS of the goal into the same normal form as `hcomp`.
      -- This is the key identity: for each `x : ι`, only the `j - degT x` component of `l x`
      -- contributes to degree `j` after multiplying by the homogeneous element `x`.
      have hlhs :
          ((DirectSum.decompose 𝒜 (Finsupp.sum l fun t r => r * (t : R))) j : R) =
            ↑((∑ x : ι,
                  (DirectSum.of (fun i => ↥(𝒜 i)) (j - degT (x : (T : Set R)))
                        ((DirectSum.decompose 𝒜 (l (x : (T : Set R)))) (j - degT (x : (T : Set R))))) *
                    (DirectSum.decompose 𝒜) (t' x)) j) := by
        -- Expand the `Finsupp.sum` as a sum over `l.support` and push `decompose` inside the sum.
        classical
        -- `Finsupp.sum` is a finset sum over `l.support`.
        -- Remaining termwise simplification uses `coe_decompose_mul_of_right_mem_of_le` and
        -- `coe_decompose_mul_of_right_mem_of_not_le`, plus the definition of `ι`.
        -- This is routine but verbose, so we leave it to simp with explicit lemmas.
        -- (Lean will reduce terms where `degT t ≤ j` using the `of_le` lemma, and otherwise to `0`.)
        -- TODO: make this fully explicit without `simp` if needed.
        simp [t', a, n', hdegTmem, DirectSum.coe_decompose_mul_of_right_mem_of_le,
          DirectSum.coe_decompose_mul_of_right_mem_of_not_le]

      -- Now finish from `hcomp`.
      -- `hcomp` has the same LHS as `hlhs` and RHS `((decompose 𝒜 y) j : R)`.
      -- Rewrite the goal using `hlhs`, then apply `hcomp`.
      -- (We use `hlhs.symm` to match the goal direction.)
      have : ↑((∑ x : ι,
              (DirectSum.of (fun i => ↥(𝒜 i)) (j - degT (x : (T : Set R)))
                    ((DirectSum.decompose 𝒜 (l (x : (T : Set R)))) (j - degT (x : (T : Set R))))) *
                (DirectSum.decompose 𝒜) (t' x)) j) =
            ((DirectSum.decompose 𝒜 y) j : R) := by
        -- rewrite via `hlhs` and then use `hcomp`
        simpa [hlhs] using hcomp
      simpa using this
    · -- degree j ≠ d component:
      -- RHS is 0 because `y ∈ 𝒜 d`.
      -- LHS should also be 0 because each term has total degree `(d - n) + n = d`.
      -- Since `y ∈ 𝒜 d`, the `j`-component is zero for `j ≠ d`.
      have hy0 : ((DirectSum.decompose 𝒜 y) j : R) = 0 := by
        simpa using (DirectSum.decompose_of_mem_ne 𝒜 hy_deg hj)
      -- It suffices to show the LHS component is also 0; each summand lies in degree `d`.
      -- TODO: provide the same bookkeeping as in the `j=d` case.
      simpa [hy0]

lemma homogeneous_mem_adjoin_of_irrelevant_eq_span
    {T : Finset R}
    (hspan : Ideal.span (T : Set R) = irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜))
    (hT : ∀ t ∈ T, ∃ d : ℕ, 0 < d ∧ t ∈ 𝒜 d) :
    ∀ d : ℕ, ∀ y : R, y ∈ 𝒜 d → y ∈ Algebra.adjoin (𝒜 0) (T : Set R) := by
  classical
  -- We prove the claim by strong induction on `d`.
  intro d
  refine Nat.strong_induction_on d ?_
  intro d ih y hy
  by_cases hd0 : d = 0
  · -- degree 0: `y` comes from the base algebra `𝒜 0`.
    subst hd0
    -- View `y` as an element of `𝒜 0` and use `Subalgebra.algebraMap_mem`.
    -- (The `Algebra (𝒜 0) R` instance is provided by Step 3.)
    have : y ∈ (Algebra.adjoin (𝒜 0) (T : Set R) : Subalgebra (𝒜 0) R) := by
      -- `⟨y, hy⟩ : 𝒜 0` maps to `y` in `R`.
      simpa using (Subalgebra.algebraMap_mem (Algebra.adjoin (𝒜 0) (T : Set R)) ⟨y, hy⟩)
    exact this
  · -- positive degree:
    have hdpos : 0 < d := Nat.pos_of_ne_zero hd0
    -- First show `y ∈ irrelevantIdeal`.
    have hy_irrel : y ∈ irrelevantIdeal (k := k) (R := R) (𝒜 := 𝒜) := by
      -- `HomogeneousIdeal.mem_irrelevant_of_mem` gives membership in the *homogeneous* ideal.
      have : y ∈ HomogeneousIdeal.irrelevant 𝒜 := by
        exact HomogeneousIdeal.mem_irrelevant_of_mem (𝒜 := 𝒜) (x := y) (i := d) hdpos hy
      -- Coerce to the underlying ideal.
      simpa [irrelevantIdeal] using this
    -- Rewrite using the spanning hypothesis.
    have hy_span : y ∈ Ideal.span (T : Set R) := by
      -- `hspan : Ideal.span T = irrelevantIdeal`, so use it backwards.
      simpa [hspan] using hy_irrel
    -- Use the auxiliary representation lemma to get a sum of products with smaller-degree coeffs.
    rcases
      exists_sum_representation_with_smaller_degree_coeffs (𝒜 := 𝒜)
        (T := T) (d := d) (y := y) hy hdpos hy_span hT with
      ⟨ι, hfin, a, t, n, htT, ht_hom, ha_small, hsum⟩
    classical
    letI : Fintype ι := hfin
    -- Each `a i` has smaller degree, so by IH it lies in the adjoin.
    have ha_mem : ∀ i : ι, a i ∈ Algebra.adjoin (𝒜 0) (T : Set R) := by
      intro i
      rcases ha_small i with ⟨m, hm_lt, ham⟩
      -- apply IH at degree `m < d`
      exact ih m hm_lt (a i) ham
    -- Each `t i` is a generator, hence is in the adjoin.
    have ht_mem : ∀ i : ι, t i ∈ Algebra.adjoin (𝒜 0) (T : Set R) := by
      intro i
      have : t i ∈ (T : Set R) := by
        exact (Finset.mem_coe.2 (htT i))
      exact Algebra.subset_adjoin this
    -- Close under multiplication and finite sums in the subalgebra.
    have : (∑ i : ι, a i * t i) ∈ Algebra.adjoin (𝒜 0) (T : Set R) := by
      classical
      -- `∑ i, ...` is notation for `Finset.sum Finset.univ`.
      -- Use `Subsemiring.sum_mem` and `Subsemiring.mul_mem` via the `toSubsemiring` coercion.
      refine (Subsemiring.sum_mem (Algebra.adjoin (𝒜 0) (T : Set R)).toSubsemiring) ?_
      intro i _
      exact
        (Subsemiring.mul_mem (Algebra.adjoin (𝒜 0) (T : Set R)).toSubsemiring (ha_mem i) (ht_mem i))
    simpa [hsum] using this

/- Step 5: package the induction into a `FiniteType (𝒜 0) R` statement.

Once you know every element of `R` lies in `Algebra.adjoin (𝒜 0) T`, you conclude the adjoin is `⊤`,
and therefore `R` is `FiniteType` over `𝒜 0`.